//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.6.1.0
        ///Incognito
        ///Korot - Update
        ///Update available.Do you want to update?
        ///Error while checking for the updates.
        ///New Tab
        ///(Note: Searched text will be put after the url)
        ///Write Custom Search Url
        ///New Window
        ///New Incognito Window
        ///Settings
        ///History
        ///Home Page:
        ///Search Engine:
        ///Theme
        ///Custom
        ///Remove Selected
        ///Background Style:
        ///Clear
        ///About
        ///Go Back
        ///Go Forward
        ///Refresh
        ///Refresh (No Cache)
        ///Stop
        ///Select All
        ///Open Link in New Tab
        ///Copy Link
        ///Save Image as...
        ///Open Image in New Tab
        ///Paste
        ///Copy
        ///Cut
        ///Undo
        ///R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0610 {
            get {
                return ResourceManager.GetString("_0610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Language&gt;
        ///&lt;Item Name=&quot;CompatibleVersion&quot; Text=&quot;0.7.0.0&quot; /&gt;
        ///&lt;Item Name=&quot;Incognito&quot; Text=&quot;Incognito&quot; /&gt;
        ///&lt;Item Name=&quot;KorotUpdate&quot; Text=&quot;Korot - Update&quot; /&gt;
        ///&lt;Item Name=&quot;KorotUpdateAvailable&quot; Text=&quot;Update available.Do you want to update?&quot; /&gt;
        ///&lt;Item Name=&quot;KorotUpdateError&quot; Text=&quot;Error while checking for the updates.&quot; /&gt;
        ///&lt;Item Name=&quot;NewTab&quot; Text=&quot;New Tab&quot; /&gt;
        ///&lt;Item Name=&quot;SearchEngineInfo&quot; Text=&quot;(Note: Searched text will be put after the url)&quot; /&gt;
        ///&lt;Item Name=&quot;SearchengineTitle&quot; Text=&quot;Write Custom Search Url&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0700 {
            get {
                return ResourceManager.GetString("_0700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btNotification.ButtonText = 324;
        ///            lbNotifSetting.Text = 325;
        ///            tpNotification.Text = 325;
        ///            lbPlayNotifSound.Text = 326;
        ///            lbSilentMode.Text = 327;
        ///            lbSchedule.Text = 328;
        ///            scheduleFrom.Text = 329;
        ///            scheduleTo.Text = 330;
        ///            lb24HType.Text = 331;
        ///            scheduleEvery.Text = 332;
        ///            lbSunday.Text = 333;
        ///            lbMonday.Text = 334;
        ///            lbTuesday.Text = 335;
        ///            lbWednesday.Text =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string replaceme {
            get {
                return ResourceManager.GetString("replaceme", resourceCulture);
            }
        }
    }
}
