//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korot_Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Korot_Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\[FILEEXT]\OpenWithProgids]
        ///&quot;[APPNAME]&quot;=&quot;&quot;
        ///[HKEY_CLASSES_ROOT\[APPNAME]\shell\open\command]
        ///@=&quot;\&quot;[APPPATH]&quot; \&quot;%1\&quot;&quot;
        ///
        /// benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileExtTemplate {
            get {
                return ResourceManager.GetString("FileExtTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Korot {
            get {
                object obj = ResourceManager.GetObject("Korot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ECHO OFF
        ///echo Please wait...
        ///&apos;sets the name of your app to display
        ///reg add &quot;HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Yourapp&quot; /v &quot;DisplayName&quot; /d &quot;[APPNAME]&quot; /f 
        ///&apos;sets your app version to display
        ///REG ADD &quot;HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Yourapp&quot; /V &quot;DisplayVersion&quot; /D &quot;[APPVERSION]&quot;
        ///&apos;sets your app icon to display location
        ///REG ADD &quot;HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Yourapp&quot; /V &quot;DisplayIcon&quot; /D &quot;[APPPATH]&quot;
        ///&apos;sets your name to display as pu [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
    }
}
